name: debugger-action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
