name: Publish modelbox images-u20
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new image tag(e.g. v1.1.0)'
        required: true
        default: 'latest'

env:
  BUILD_TYPE: Release
  IMAGE_VERSION: ${{ github.event.inputs.version }}

jobs:
  compile_x86d_ubuntu:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME_DEV: ${{ steps.env.outputs.IMAGE_NAME_DEV }}
      IMAGE_NAME_RUN: ${{ steps.env.outputs.IMAGE_NAME_RUN }}
    steps:
    - name: Set-env
      id: env
      run: |
        echo "::set-output name=IMAGE_NAME_DEV::zxk114/modelbox-develop-mindspore_1.6.1-cann_5.0.4-ubuntu-x86_64"
        echo "::set-output name=IMAGE_NAME_RUN::zxk114/modelbox-runtime-mindspore_1.6.1-cann_5.0.4-ubuntu-x86_64"
    - name: Checkout
      uses: actions/checkout@v3

  build_x86d_ubuntu_develop_image:
    runs-on: ubuntu-22.04
    needs: compile_x86d_ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_ZXK }}
          password: ${{ secrets.DOCKERHUB_TOKEN_ZXK }}
      - name: Download for dev package
        run: |
            sed -i '55d' docker/prepare_for_dev.sh
            sed -i '4d' docker/Dockerfile.ascend.develop.ubuntu-u2
            bash docker/prepare_for_dev.sh
        shell: bash
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: docker/Dockerfile.ascend.develop.ubuntu-u2
          tags: |
            ${{ needs.compile_x86d_ubuntu.outputs.IMAGE_NAME_DEV }}:latest
            ${{ needs.compile_x86d_ubuntu.outputs.IMAGE_NAME_DEV }}:${{ env.IMAGE_VERSION }}
